version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: Assistant_Backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://test:123456@postgres:5432/test_db
      OPENAI_API_KEY: dein_api_key
    depends_on:
      - postgres

volumes:
  postgres_data:
