FROM node:20-alpine

WORKDIR /app

# Dependencies installing
COPY package*.json ./
RUN npm install

# Generating Prisma Client for Linux 
COPY prisma ./prisma
RUN npx prisma generate

# Copy source code 
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]