services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: ai_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - dev-network
      
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: ai_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - dev-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: ai_nextjs
    restart: always
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - /app/node_modules
    networks:
      - dev-network
      
volumes:
  db_data:

networks:
  dev-network:
    driver: bridge